
package au.net.electronichealth.ns.hi.svc.consumerresolveprovisionalihi._3_0;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerResolveProvisionalIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2", wsdlLocation = "HI_ConsumerResolveProvisionalIHI-3.0.2.wsdl")
public class ConsumerResolveProvisionalIHIService
    extends Service
{

    private static final URL CONSUMERRESOLVEPROVISIONALIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERRESOLVEPROVISIONALIHISERVICE_EXCEPTION;
    private static final QName CONSUMERRESOLVEPROVISIONALIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2", "ConsumerResolveProvisionalIHIService");

    static {
        CONSUMERRESOLVEPROVISIONALIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumerresolveprovisionalihi._3_0.ConsumerResolveProvisionalIHIService.class.getResource("HI_ConsumerResolveProvisionalIHI-3.0.2.wsdl");
        WebServiceException e = null;
        if (CONSUMERRESOLVEPROVISIONALIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerResolveProvisionalIHI-3.0.2.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERRESOLVEPROVISIONALIHISERVICE_EXCEPTION = e;
    }

    public ConsumerResolveProvisionalIHIService() {
        super(__getWsdlLocation(), CONSUMERRESOLVEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerResolveProvisionalIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERRESOLVEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerResolveProvisionalIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERRESOLVEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerResolveProvisionalIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERRESOLVEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerResolveProvisionalIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerResolveProvisionalIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerResolveProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerResolveProvisionalIHISOAP12Port")
    public ConsumerResolveProvisionalIHIPortType getConsumerResolveProvisionalIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2", "ConsumerResolveProvisionalIHISOAP12Port"), ConsumerResolveProvisionalIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerResolveProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerResolveProvisionalIHISOAP12Port")
    public ConsumerResolveProvisionalIHIPortType getConsumerResolveProvisionalIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2", "ConsumerResolveProvisionalIHISOAP12Port"), ConsumerResolveProvisionalIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERRESOLVEPROVISIONALIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERRESOLVEPROVISIONALIHISERVICE_EXCEPTION;
        }
        return CONSUMERRESOLVEPROVISIONALIHISERVICE_WSDL_LOCATION;
    }

}
