
package au.net.electronichealth.ns.hi.svc.providersearchtdsproviderindividual._5_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderSearchTdsProviderIndividualService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchTdsProviderIndividual/5.1.0", wsdlLocation = "/HI_ProviderSearchTdsProviderIndividual-5.1.0.wsdl")
public class ProviderSearchTdsProviderIndividualService
    extends Service
{

    private final static URL PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_EXCEPTION;
    private final static QName PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchTdsProviderIndividual/5.1.0", "ProviderSearchTdsProviderIndividualService");

    static {
        PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providersearchtdsproviderindividual._5_1.ProviderSearchTdsProviderIndividualService.class.getResource("/HI_ProviderSearchTdsProviderIndividual-5.1.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/HI_ProviderSearchTdsProviderIndividual-5.1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_EXCEPTION = e;
    }

    public ProviderSearchTdsProviderIndividualService() {
        super(__getWsdlLocation(), PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_QNAME);
    }

    public ProviderSearchTdsProviderIndividualService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderSearchTdsProviderIndividualService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_QNAME);
    }

    public ProviderSearchTdsProviderIndividualService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderSearchTdsProviderIndividualService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderSearchTdsProviderIndividualService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderSearchTdsProviderIndividualPortType
     */
    @WebEndpoint(name = "ProviderSearchTdsProviderIndividualPort")
    public ProviderSearchTdsProviderIndividualPortType getProviderSearchTdsProviderIndividualPort() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchTdsProviderIndividual/5.1.0", "ProviderSearchTdsProviderIndividualPort"), ProviderSearchTdsProviderIndividualPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderSearchTdsProviderIndividualPortType
     */
    @WebEndpoint(name = "ProviderSearchTdsProviderIndividualPort")
    public ProviderSearchTdsProviderIndividualPortType getProviderSearchTdsProviderIndividualPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchTdsProviderIndividual/5.1.0", "ProviderSearchTdsProviderIndividualPort"), ProviderSearchTdsProviderIndividualPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_EXCEPTION!= null) {
            throw PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_EXCEPTION;
        }
        return PROVIDERSEARCHTDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION;
    }

}
