
package au.net.electronichealth.ns.hi.svc.providersearchhiproviderdirectoryfororganisation._3_2;

import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ProductType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.SignatureContainerType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.TimestampType;
import au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.QualifiedId;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProviderSearchHIProviderDirectoryForOrganisationPortType", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.hi.svc.providersearchhiproviderdirectoryfororganisation._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.addresscore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.electroniccommunicationcore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.individualnamecore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.address._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.electroniccommunication._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.elements._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.endpoint._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.individualname._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.linkedtype._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.organisationdetails._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.organisationname._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.organisationservice._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providermessages.searchorganisation._3_2.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoredatatypes._3.ObjectFactory.class
})
public interface ProviderSearchHIProviderDirectoryForOrganisationPortType {


    /**
     * 
     * @param hpioHeader
     * @param productHeader
     * @param request
     * @param signatureHeader
     * @param timestampHeader
     * @param userHeader
     * @return
     *     returns au.net.electronichealth.ns.hi.svc.providersearchhiproviderdirectoryfororganisation._3_2.SearchHIProviderDirectoryForOrganisationResponse
     * @throws StandardErrorMsg
     */
    @WebMethod
    @WebResult(name = "searchHIProviderDirectoryForOrganisationResponse", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0", partName = "response")
    @Action(input = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0/ProviderSearchHIProviderDirectoryForOrganisationPortType/searchHIProviderDirectoryForOrganisationRequest", output = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0/ProviderSearchHIProviderDirectoryForOrganisationPortType/searchHIProviderDirectoryForOrganisationResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0/ProviderSearchHIProviderDirectoryForOrganisationPortType/searchHIProviderDirectoryForOrganisation/Fault/standardError")
    })
    public SearchHIProviderDirectoryForOrganisationResponse searchHIProviderDirectoryForOrganisation(
        @WebParam(name = "searchHIProviderDirectoryForOrganisation", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForOrganisation/3.2.0", partName = "request")
        SearchHIProviderDirectoryForOrganisation request,
        @WebParam(name = "product", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "productHeader")
        Holder<ProductType> productHeader,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "timestampHeader")
        TimestampType timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<SignatureContainerType> signatureHeader,
        @WebParam(name = "user", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "userHeader")
        QualifiedId userHeader,
        @WebParam(name = "hpio", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "hpioHeader")
        QualifiedId hpioHeader)
        throws StandardErrorMsg
    ;

}
