
package au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderorganisation._5_1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProviderSearchForOrganisationBatchAsyncService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderOrganisation/5.1.0", wsdlLocation = "HI_ProviderBatchAsyncSearchForProviderOrganisation-5.1.0.wsdl")
public class ProviderSearchForOrganisationBatchAsyncService
    extends Service
{

    private static final URL PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_WSDL_LOCATION;
    private static final WebServiceException PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_EXCEPTION;
    private static final QName PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderOrganisation/5.1.0", "ProviderSearchForOrganisationBatchAsyncService");

    static {
        PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderorganisation._5_1.ProviderSearchForOrganisationBatchAsyncService.class.getResource("HI_ProviderBatchAsyncSearchForProviderOrganisation-5.1.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderBatchAsyncSearchForProviderOrganisation-5.1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_EXCEPTION = e;
    }

    public ProviderSearchForOrganisationBatchAsyncService() {
        super(__getWsdlLocation(), PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_QNAME);
    }

    public ProviderSearchForOrganisationBatchAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_QNAME, features);
    }

    public ProviderSearchForOrganisationBatchAsyncService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_QNAME);
    }

    public ProviderSearchForOrganisationBatchAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_QNAME, features);
    }

    public ProviderSearchForOrganisationBatchAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderSearchForOrganisationBatchAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchForProviderOrganisationBatchAsyncPortType
     */
    @WebEndpoint(name = "ProviderSearchForIOrganisationBatchAsyncPort")
    public SearchForProviderOrganisationBatchAsyncPortType getProviderSearchForIOrganisationBatchAsyncPort() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderOrganisation/5.1.0", "ProviderSearchForIOrganisationBatchAsyncPort"), SearchForProviderOrganisationBatchAsyncPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchForProviderOrganisationBatchAsyncPortType
     */
    @WebEndpoint(name = "ProviderSearchForIOrganisationBatchAsyncPort")
    public SearchForProviderOrganisationBatchAsyncPortType getProviderSearchForIOrganisationBatchAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderOrganisation/5.1.0", "ProviderSearchForIOrganisationBatchAsyncPort"), SearchForProviderOrganisationBatchAsyncPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_EXCEPTION!= null) {
            throw PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_EXCEPTION;
        }
        return PROVIDERSEARCHFORORGANISATIONBATCHASYNCSERVICE_WSDL_LOCATION;
    }

}
