
package au.net.electronichealth.ns.hi.svc.consumernotifyreplicaihi._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerNotifyReplicaIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyReplicaIHI/3.2.0", wsdlLocation = "HI_ConsumerNotifyReplicaIHI-3.2.0.wsdl")
public class ConsumerNotifyReplicaIHIService
    extends Service
{

    private static final URL CONSUMERNOTIFYREPLICAIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERNOTIFYREPLICAIHISERVICE_EXCEPTION;
    private static final QName CONSUMERNOTIFYREPLICAIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyReplicaIHI/3.2.0", "ConsumerNotifyReplicaIHIService");

    static {
        CONSUMERNOTIFYREPLICAIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumernotifyreplicaihi._3_2.ConsumerNotifyReplicaIHIService.class.getResource("HI_ConsumerNotifyReplicaIHI-3.2.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERNOTIFYREPLICAIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerNotifyReplicaIHI-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERNOTIFYREPLICAIHISERVICE_EXCEPTION = e;
    }

    public ConsumerNotifyReplicaIHIService() {
        super(__getWsdlLocation(), CONSUMERNOTIFYREPLICAIHISERVICE_QNAME);
    }

    public ConsumerNotifyReplicaIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERNOTIFYREPLICAIHISERVICE_QNAME, features);
    }

    public ConsumerNotifyReplicaIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERNOTIFYREPLICAIHISERVICE_QNAME);
    }

    public ConsumerNotifyReplicaIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERNOTIFYREPLICAIHISERVICE_QNAME, features);
    }

    public ConsumerNotifyReplicaIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerNotifyReplicaIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerNotifyReplicaIHIPortType
     */
    @WebEndpoint(name = "ConsumerNotifyReplicaIHISOAP12Port")
    public ConsumerNotifyReplicaIHIPortType getConsumerNotifyReplicaIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyReplicaIHI/3.2.0", "ConsumerNotifyReplicaIHISOAP12Port"), ConsumerNotifyReplicaIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerNotifyReplicaIHIPortType
     */
    @WebEndpoint(name = "ConsumerNotifyReplicaIHISOAP12Port")
    public ConsumerNotifyReplicaIHIPortType getConsumerNotifyReplicaIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyReplicaIHI/3.2.0", "ConsumerNotifyReplicaIHISOAP12Port"), ConsumerNotifyReplicaIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERNOTIFYREPLICAIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERNOTIFYREPLICAIHISERVICE_EXCEPTION;
        }
        return CONSUMERNOTIFYREPLICAIHISERVICE_WSDL_LOCATION;
    }

}
