
package au.net.electronichealth.ns.hi.svc.consumernotifyduplicateihi._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerNotifyDuplicateIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyDuplicateIHI/3.2.0", wsdlLocation = "HI_ConsumerNotifyDuplicateIHI-3.2.0.wsdl")
public class ConsumerNotifyDuplicateIHIService
    extends Service
{

    private static final URL CONSUMERNOTIFYDUPLICATEIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERNOTIFYDUPLICATEIHISERVICE_EXCEPTION;
    private static final QName CONSUMERNOTIFYDUPLICATEIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyDuplicateIHI/3.2.0", "ConsumerNotifyDuplicateIHIService");

    static {
        CONSUMERNOTIFYDUPLICATEIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumernotifyduplicateihi._3_2.ConsumerNotifyDuplicateIHIService.class.getResource("HI_ConsumerNotifyDuplicateIHI-3.2.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERNOTIFYDUPLICATEIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerNotifyDuplicateIHI-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERNOTIFYDUPLICATEIHISERVICE_EXCEPTION = e;
    }

    public ConsumerNotifyDuplicateIHIService() {
        super(__getWsdlLocation(), CONSUMERNOTIFYDUPLICATEIHISERVICE_QNAME);
    }

    public ConsumerNotifyDuplicateIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERNOTIFYDUPLICATEIHISERVICE_QNAME, features);
    }

    public ConsumerNotifyDuplicateIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERNOTIFYDUPLICATEIHISERVICE_QNAME);
    }

    public ConsumerNotifyDuplicateIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERNOTIFYDUPLICATEIHISERVICE_QNAME, features);
    }

    public ConsumerNotifyDuplicateIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerNotifyDuplicateIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerNotifyDuplicateIHIPortType
     */
    @WebEndpoint(name = "ConsumerNotifyDuplicateIHISOAP12Port")
    public ConsumerNotifyDuplicateIHIPortType getConsumerNotifyDuplicateIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyDuplicateIHI/3.2.0", "ConsumerNotifyDuplicateIHISOAP12Port"), ConsumerNotifyDuplicateIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerNotifyDuplicateIHIPortType
     */
    @WebEndpoint(name = "ConsumerNotifyDuplicateIHISOAP12Port")
    public ConsumerNotifyDuplicateIHIPortType getConsumerNotifyDuplicateIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerNotifyDuplicateIHI/3.2.0", "ConsumerNotifyDuplicateIHISOAP12Port"), ConsumerNotifyDuplicateIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERNOTIFYDUPLICATEIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERNOTIFYDUPLICATEIHISERVICE_EXCEPTION;
        }
        return CONSUMERNOTIFYDUPLICATEIHISERVICE_WSDL_LOCATION;
    }

}
