
package au.net.electronichealth.ns.hi.svc.providermanageproviderorganisation._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderManageProviderOrganisationService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderManageProviderOrganisation/3.2.0", wsdlLocation = "HI_ProviderManageProviderOrganisation-3.2.0.wsdl")
public class ProviderManageProviderOrganisationService
    extends Service
{

    private final static URL PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_EXCEPTION;
    private final static QName PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageProviderOrganisation/3.2.0", "ProviderManageProviderOrganisationService");

    static {
        PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providermanageproviderorganisation._3_2.ProviderManageProviderOrganisationService.class.getResource("HI_ProviderManageProviderOrganisation-3.2.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderManageProviderOrganisation-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_EXCEPTION = e;
    }

    public ProviderManageProviderOrganisationService() {
        super(__getWsdlLocation(), PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_QNAME);
    }

    public ProviderManageProviderOrganisationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_QNAME, features);
    }

    public ProviderManageProviderOrganisationService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_QNAME);
    }

    public ProviderManageProviderOrganisationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_QNAME, features);
    }

    public ProviderManageProviderOrganisationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderManageProviderOrganisationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderManageProviderOrganisationPortType
     */
    @WebEndpoint(name = "ProviderManageProviderOrganisationSOAP12Port")
    public ProviderManageProviderOrganisationPortType getProviderManageProviderOrganisationSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageProviderOrganisation/3.2.0", "ProviderManageProviderOrganisationSOAP12Port"), ProviderManageProviderOrganisationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderManageProviderOrganisationPortType
     */
    @WebEndpoint(name = "ProviderManageProviderOrganisationSOAP12Port")
    public ProviderManageProviderOrganisationPortType getProviderManageProviderOrganisationSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageProviderOrganisation/3.2.0", "ProviderManageProviderOrganisationSOAP12Port"), ProviderManageProviderOrganisationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_EXCEPTION!= null) {
            throw PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_EXCEPTION;
        }
        return PROVIDERMANAGEPROVIDERORGANISATIONSERVICE_WSDL_LOCATION;
    }

}
