
package au.net.electronichealth.ns.hi.svc.providersearchhiproviderdirectoryforindividual._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderSearchHIProviderDirectoryForIndividualService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForIndividual/3.2.0", wsdlLocation = "HI_ProviderSearchHIProviderDirectoryForIndividual-3.2.0.wsdl")
public class ProviderSearchHIProviderDirectoryForIndividualService
    extends Service
{

    private final static URL PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_EXCEPTION;
    private final static QName PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForIndividual/3.2.0", "ProviderSearchHIProviderDirectoryForIndividualService");

    static {
        PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providersearchhiproviderdirectoryforindividual._3_2.ProviderSearchHIProviderDirectoryForIndividualService.class.getResource("HI_ProviderSearchHIProviderDirectoryForIndividual-3.2.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderSearchHIProviderDirectoryForIndividual-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_EXCEPTION = e;
    }

    public ProviderSearchHIProviderDirectoryForIndividualService() {
        super(__getWsdlLocation(), PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_QNAME);
    }

    public ProviderSearchHIProviderDirectoryForIndividualService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderSearchHIProviderDirectoryForIndividualService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_QNAME);
    }

    public ProviderSearchHIProviderDirectoryForIndividualService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderSearchHIProviderDirectoryForIndividualService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderSearchHIProviderDirectoryForIndividualService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderSearchHIProviderDirectoryForIndividualPortType
     */
    @WebEndpoint(name = "ProviderSearchHIProviderDirectoryForIndividualSOAP12Port")
    public ProviderSearchHIProviderDirectoryForIndividualPortType getProviderSearchHIProviderDirectoryForIndividualSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForIndividual/3.2.0", "ProviderSearchHIProviderDirectoryForIndividualSOAP12Port"), ProviderSearchHIProviderDirectoryForIndividualPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderSearchHIProviderDirectoryForIndividualPortType
     */
    @WebEndpoint(name = "ProviderSearchHIProviderDirectoryForIndividualSOAP12Port")
    public ProviderSearchHIProviderDirectoryForIndividualPortType getProviderSearchHIProviderDirectoryForIndividualSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchHIProviderDirectoryForIndividual/3.2.0", "ProviderSearchHIProviderDirectoryForIndividualSOAP12Port"), ProviderSearchHIProviderDirectoryForIndividualPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_EXCEPTION!= null) {
            throw PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_EXCEPTION;
        }
        return PROVIDERSEARCHHIPROVIDERDIRECTORYFORINDIVIDUALSERVICE_WSDL_LOCATION;
    }

}
