
package au.net.electronichealth.ns.hi.svc.providermanagetdsproviderindividual._5_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderManageTdsProviderIndividualService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", wsdlLocation = "/HI_ProviderManageTdsProviderIndividual-5.1.0.wsdl")
public class ProviderManageTdsProviderIndividualService
    extends Service
{

    private final static URL PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_EXCEPTION;
    private final static QName PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", "ProviderManageTdsProviderIndividualService");

    static {
        PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providermanagetdsproviderindividual._5_1.ProviderManageTdsProviderIndividualService.class.getResource("/HI_ProviderManageTdsProviderIndividual-5.1.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/HI_ProviderManageTdsProviderIndividual-5.1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_EXCEPTION = e;
    }

    public ProviderManageTdsProviderIndividualService() {
        super(__getWsdlLocation(), PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_QNAME);
    }

    public ProviderManageTdsProviderIndividualService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderManageTdsProviderIndividualService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_QNAME);
    }

    public ProviderManageTdsProviderIndividualService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderManageTdsProviderIndividualService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderManageTdsProviderIndividualService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderManageTdsProviderIndividualPortType
     */
    @WebEndpoint(name = "ProviderManageTdsProviderIndividualSOAP12Port")
    public ProviderManageTdsProviderIndividualPortType getProviderManageTdsProviderIndividualSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", "ProviderManageTdsProviderIndividualSOAP12Port"), ProviderManageTdsProviderIndividualPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderManageTdsProviderIndividualPortType
     */
    @WebEndpoint(name = "ProviderManageTdsProviderIndividualSOAP12Port")
    public ProviderManageTdsProviderIndividualPortType getProviderManageTdsProviderIndividualSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", "ProviderManageTdsProviderIndividualSOAP12Port"), ProviderManageTdsProviderIndividualPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_EXCEPTION!= null) {
            throw PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_EXCEPTION;
        }
        return PROVIDERMANAGETDSPROVIDERINDIVIDUALSERVICE_WSDL_LOCATION;
    }

}
