
package au.net.electronichealth.ns.hi.svc.providermanagetdsproviderindividual._5_1;

import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ProductType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.SignatureContainerType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.TimestampType;
import au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.QualifiedId;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProviderManageTdsProviderIndividualPortType", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.gov.medicareaustralia.ns.provider.schema._2013._06._22.elements.ObjectFactory.class,
    au.net.electronichealth.ns.hi.svc.providermanagetdsproviderindividual._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.addresscore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.electroniccommunicationcore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.individualnamecore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.address._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.address._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.certificate._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.electroniccommunication._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.electroniccommunication._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.elements._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.individualname._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.individualname._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.personaldetails._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providertype._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providertype._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.status._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providermessages.managetdsproviderindividual._3_2.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoredatatypes._3.ObjectFactory.class
})
public interface ProviderManageTdsProviderIndividualPortType {


    /**
     * 
     * @param productHeader
     * @param request
     * @param signatureHeader
     * @param timestampHeader
     * @param userHeader
     * @return
     *     returns au.net.electronichealth.ns.hi.svc.providermanagetdsproviderindividual._5_1.ManageTdsProviderIndividualResponse
     * @throws StandardErrorMsg
     */
    @WebMethod
    @WebResult(name = "manageTdsProviderIndividualResponse", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", partName = "response")
    @Action(input = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0/ProviderManageTdsProviderIndividualPortType/manageTdsProviderIndividualRequest", output = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0/ProviderManageTdsProviderIndividualPortType/manageTdsProviderIndividualResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0/ProviderManageTdsProviderIndividualPortType/manageTdsProviderIndividual/Fault/standardError")
    })
    public ManageTdsProviderIndividualResponse manageTdsProviderIndividual(
        @WebParam(name = "manageTdsProviderIndividual", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderManageTdsProviderIndividual/5.1.0", partName = "request")
        ManageTdsProviderIndividual request,
        @WebParam(name = "product", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "productHeader")
        Holder<ProductType> productHeader,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "timestampHeader")
        TimestampType timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<SignatureContainerType> signatureHeader,
        @WebParam(name = "user", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "userHeader")
        QualifiedId userHeader)
        throws StandardErrorMsg
    ;

}
