
package au.net.electronichealth.ns.hi.svc.providerreadprovideradministrativeindividual._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderReadProviderAdministrativeIndividualService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderReadProviderAdministrativeIndividual/3.2.0", wsdlLocation = "HI_ProviderReadProviderAdministrativeIndividual-3.2.0.wsdl")
public class ProviderReadProviderAdministrativeIndividualService
    extends Service
{

    private final static URL PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_EXCEPTION;
    private final static QName PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadProviderAdministrativeIndividual/3.2.0", "ProviderReadProviderAdministrativeIndividualService");

    static {
        PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providerreadprovideradministrativeindividual._3_2.ProviderReadProviderAdministrativeIndividualService.class.getResource("HI_ProviderReadProviderAdministrativeIndividual-3.2.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderReadProviderAdministrativeIndividual-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_EXCEPTION = e;
    }

    public ProviderReadProviderAdministrativeIndividualService() {
        super(__getWsdlLocation(), PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_QNAME);
    }

    public ProviderReadProviderAdministrativeIndividualService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderReadProviderAdministrativeIndividualService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_QNAME);
    }

    public ProviderReadProviderAdministrativeIndividualService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_QNAME, features);
    }

    public ProviderReadProviderAdministrativeIndividualService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderReadProviderAdministrativeIndividualService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderReadProviderAdministrativeIndividualPortType
     */
    @WebEndpoint(name = "ProviderReadProviderAdministrativeIndividualSOAP12Port")
    public ProviderReadProviderAdministrativeIndividualPortType getProviderReadProviderAdministrativeIndividualSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadProviderAdministrativeIndividual/3.2.0", "ProviderReadProviderAdministrativeIndividualSOAP12Port"), ProviderReadProviderAdministrativeIndividualPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderReadProviderAdministrativeIndividualPortType
     */
    @WebEndpoint(name = "ProviderReadProviderAdministrativeIndividualSOAP12Port")
    public ProviderReadProviderAdministrativeIndividualPortType getProviderReadProviderAdministrativeIndividualSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadProviderAdministrativeIndividual/3.2.0", "ProviderReadProviderAdministrativeIndividualSOAP12Port"), ProviderReadProviderAdministrativeIndividualPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_EXCEPTION!= null) {
            throw PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_EXCEPTION;
        }
        return PROVIDERREADPROVIDERADMINISTRATIVEINDIVIDUALSERVICE_WSDL_LOCATION;
    }

}
