
package au.net.electronichealth.ns.hi.svc.providerreadprovideradministrativeindividual._3_2;

import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ServiceMessagesType;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "serviceMessages", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")
public class StandardErrorMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceMessagesType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public StandardErrorMsg(String message, ServiceMessagesType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public StandardErrorMsg(String message, ServiceMessagesType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ServiceMessagesType
     */
    public ServiceMessagesType getFaultInfo() {
        return faultInfo;
    }

}
