
package au.net.electronichealth.ns.hi.svc.consumercreateverifiedihi._4_0;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerCreateVerifiedIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerCreateVerifiedIHI/4.0.0", wsdlLocation = "HI_ConsumerCreateVerifiedIHI-4.0.0.wsdl")
public class ConsumerCreateVerifiedIHIService
    extends Service
{

    private static final URL CONSUMERCREATEVERIFIEDIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERCREATEVERIFIEDIHISERVICE_EXCEPTION;
    private static final QName CONSUMERCREATEVERIFIEDIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateVerifiedIHI/4.0.0", "ConsumerCreateVerifiedIHIService");

    static {
        CONSUMERCREATEVERIFIEDIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumercreateverifiedihi._4_0.ConsumerCreateVerifiedIHIService.class.getResource("HI_ConsumerCreateVerifiedIHI-4.0.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERCREATEVERIFIEDIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerCreateVerifiedIHI-4.0.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERCREATEVERIFIEDIHISERVICE_EXCEPTION = e;
    }

    public ConsumerCreateVerifiedIHIService() {
        super(__getWsdlLocation(), CONSUMERCREATEVERIFIEDIHISERVICE_QNAME);
    }

    public ConsumerCreateVerifiedIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERCREATEVERIFIEDIHISERVICE_QNAME, features);
    }

    public ConsumerCreateVerifiedIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERCREATEVERIFIEDIHISERVICE_QNAME);
    }

    public ConsumerCreateVerifiedIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERCREATEVERIFIEDIHISERVICE_QNAME, features);
    }

    public ConsumerCreateVerifiedIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerCreateVerifiedIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerCreateVerifiedIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateVerifiedIHISOAP12Port")
    public ConsumerCreateVerifiedIHIPortType getConsumerCreateVerifiedIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateVerifiedIHI/4.0.0", "ConsumerCreateVerifiedIHISOAP12Port"), ConsumerCreateVerifiedIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerCreateVerifiedIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateVerifiedIHISOAP12Port")
    public ConsumerCreateVerifiedIHIPortType getConsumerCreateVerifiedIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateVerifiedIHI/4.0.0", "ConsumerCreateVerifiedIHISOAP12Port"), ConsumerCreateVerifiedIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERCREATEVERIFIEDIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERCREATEVERIFIEDIHISERVICE_EXCEPTION;
        }
        return CONSUMERCREATEVERIFIEDIHISERVICE_WSDL_LOCATION;
    }

}
