
package au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsumerMergeProvisionalIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", wsdlLocation = "/HI_ConsumerMergeProvisionalIHI-3.0.wsdl")
public class ConsumerMergeProvisionalIHIService
    extends Service
{

    private final static URL CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION;
    private final static QName CONSUMERMERGEPROVISIONALIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHIService");

    static {
        CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3.ConsumerMergeProvisionalIHIService.class.getResource("/HI_ConsumerMergeProvisionalIHI-3.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/HI_ConsumerMergeProvisionalIHI-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION = e;
    }

    public ConsumerMergeProvisionalIHIService() {
        super(__getWsdlLocation(), CONSUMERMERGEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerMergeProvisionalIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERMERGEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERMERGEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERMERGEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerMergeProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerMergeProvisionalIHISOAP12Port")
    public ConsumerMergeProvisionalIHIPortType getConsumerMergeProvisionalIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHISOAP12Port"), ConsumerMergeProvisionalIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerMergeProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerMergeProvisionalIHISOAP12Port")
    public ConsumerMergeProvisionalIHIPortType getConsumerMergeProvisionalIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHISOAP12Port"), ConsumerMergeProvisionalIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION;
        }
        return CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION;
    }

}
