
package au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerMergeProvisionalIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", wsdlLocation = "HI_ConsumerMergeProvisionalIHI-3.0.wsdl")
public class ConsumerMergeProvisionalIHIService
    extends Service
{

    private static final URL CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION;
    private static final QName CONSUMERMERGEPROVISIONALIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHIService");

    static {
        CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3.ConsumerMergeProvisionalIHIService.class.getResource("HI_ConsumerMergeProvisionalIHI-3.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerMergeProvisionalIHI-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION = e;
    }

    public ConsumerMergeProvisionalIHIService() {
        super(__getWsdlLocation(), CONSUMERMERGEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerMergeProvisionalIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERMERGEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERMERGEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERMERGEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerMergeProvisionalIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerMergeProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerMergeProvisionalIHISOAP12Port")
    public ConsumerMergeProvisionalIHIPortType getConsumerMergeProvisionalIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHISOAP12Port"), ConsumerMergeProvisionalIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerMergeProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerMergeProvisionalIHISOAP12Port")
    public ConsumerMergeProvisionalIHIPortType getConsumerMergeProvisionalIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", "ConsumerMergeProvisionalIHISOAP12Port"), ConsumerMergeProvisionalIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERMERGEPROVISIONALIHISERVICE_EXCEPTION;
        }
        return CONSUMERMERGEPROVISIONALIHISERVICE_WSDL_LOCATION;
    }

}
