
package au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3;

import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ProductType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.SignatureContainerType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.TimestampType;
import au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.QualifiedId;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ConsumerMergeProvisionalIHIPortType", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.consumercore.consumercoreelements._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.consumermessages.mergeprovisionalihi._3.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.consumercore.consumercoredatatypes._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoredatatypes._3.ObjectFactory.class
})
public interface ConsumerMergeProvisionalIHIPortType {


    /**
     * 
     * @param hpioHeader
     * @param productHeader
     * @param request
     * @param signatureHeader
     * @param timestampHeader
     * @param userHeader
     * @return
     *     returns au.net.electronichealth.ns.hi.svc.consumermergeprovisionalihi._3.MergeProvisionalIHIResponse
     * @throws StandardErrorMsg
     */
    @WebMethod(action = "http://ns.electronichealth.net.au/")
    @WebResult(name = "mergeProvisionalIHIResponse", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", partName = "response")
    @Action(input = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0/ConsumerMergeProvisionalIHIPortType/mergeProvisionalIHIRequest", output = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0/ConsumerMergeProvisionalIHIPortType/mergeProvisionalIHIResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0/ConsumerMergeProvisionalIHIPortType/mergeProvisionalIHI/Fault/standardError")
    })
    public MergeProvisionalIHIResponse mergeProvisionalIHI(
        @WebParam(name = "mergeProvisionalIHI", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerMergeProvisionalIHI/3.0", partName = "request")
        MergeProvisionalIHI request,
        @WebParam(name = "product", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "productHeader")
        Holder<ProductType> productHeader,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "timestampHeader")
        TimestampType timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<SignatureContainerType> signatureHeader,
        @WebParam(name = "user", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "userHeader")
        QualifiedId userHeader,
        @WebParam(name = "hpio", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "hpioHeader")
        QualifiedId hpioHeader)
        throws StandardErrorMsg
    ;

}
