
package au.net.electronichealth.ns.hi.svc.consumersearchihibatchsyncrequest._3;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsumerSearchIHIBatchSyncService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchSyncRequest/3.0", wsdlLocation = "HI_ConsumerSearchIHIBatchSync-3.0.wsdl")
public class ConsumerSearchIHIBatchSyncService
    extends Service
{

    private final static URL CONSUMERSEARCHIHIBATCHSYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSUMERSEARCHIHIBATCHSYNCSERVICE_EXCEPTION;
    private final static QName CONSUMERSEARCHIHIBATCHSYNCSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchSyncRequest/3.0", "ConsumerSearchIHIBatchSyncService");

    static {
        CONSUMERSEARCHIHIBATCHSYNCSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumersearchihibatchsyncrequest._3.ConsumerSearchIHIBatchSyncService.class.getResource("HI_ConsumerSearchIHIBatchSync-3.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERSEARCHIHIBATCHSYNCSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerSearchIHIBatchSync-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERSEARCHIHIBATCHSYNCSERVICE_EXCEPTION = e;
    }

    public ConsumerSearchIHIBatchSyncService() {
        super(__getWsdlLocation(), CONSUMERSEARCHIHIBATCHSYNCSERVICE_QNAME);
    }

    public ConsumerSearchIHIBatchSyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERSEARCHIHIBATCHSYNCSERVICE_QNAME, features);
    }

    public ConsumerSearchIHIBatchSyncService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERSEARCHIHIBATCHSYNCSERVICE_QNAME);
    }

    public ConsumerSearchIHIBatchSyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERSEARCHIHIBATCHSYNCSERVICE_QNAME, features);
    }

    public ConsumerSearchIHIBatchSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerSearchIHIBatchSyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerSearchIHIBatchSyncPortType
     */
    @WebEndpoint(name = "ConsumerSearchIHIBatchSyncSOAP12ServicePort")
    public ConsumerSearchIHIBatchSyncPortType getConsumerSearchIHIBatchSyncSOAP12ServicePort() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchSyncRequest/3.0", "ConsumerSearchIHIBatchSyncSOAP12ServicePort"), ConsumerSearchIHIBatchSyncPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerSearchIHIBatchSyncPortType
     */
    @WebEndpoint(name = "ConsumerSearchIHIBatchSyncSOAP12ServicePort")
    public ConsumerSearchIHIBatchSyncPortType getConsumerSearchIHIBatchSyncSOAP12ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchSyncRequest/3.0", "ConsumerSearchIHIBatchSyncSOAP12ServicePort"), ConsumerSearchIHIBatchSyncPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERSEARCHIHIBATCHSYNCSERVICE_EXCEPTION!= null) {
            throw CONSUMERSEARCHIHIBATCHSYNCSERVICE_EXCEPTION;
        }
        return CONSUMERSEARCHIHIBATCHSYNCSERVICE_WSDL_LOCATION;
    }

}
