
package au.net.electronichealth.ns.hi.svc.consumerupdateihi._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerUpdateIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateIHI/3.2.0", wsdlLocation = "HI_ConsumerUpdateIHI-3.2.0.wsdl")
public class ConsumerUpdateIHIService
    extends Service
{

    private static final URL CONSUMERUPDATEIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERUPDATEIHISERVICE_EXCEPTION;
    private static final QName CONSUMERUPDATEIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateIHI/3.2.0", "ConsumerUpdateIHIService");

    static {
        CONSUMERUPDATEIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumerupdateihi._3_2.ConsumerUpdateIHIService.class.getResource("HI_ConsumerUpdateIHI-3.2.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERUPDATEIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerUpdateIHI-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERUPDATEIHISERVICE_EXCEPTION = e;
    }

    public ConsumerUpdateIHIService() {
        super(__getWsdlLocation(), CONSUMERUPDATEIHISERVICE_QNAME);
    }

    public ConsumerUpdateIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERUPDATEIHISERVICE_QNAME, features);
    }

    public ConsumerUpdateIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERUPDATEIHISERVICE_QNAME);
    }

    public ConsumerUpdateIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERUPDATEIHISERVICE_QNAME, features);
    }

    public ConsumerUpdateIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerUpdateIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerUpdateIHIPortType
     */
    @WebEndpoint(name = "ConsumerUpdateIHISOAP12Port")
    public ConsumerUpdateIHIPortType getConsumerUpdateIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateIHI/3.2.0", "ConsumerUpdateIHISOAP12Port"), ConsumerUpdateIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerUpdateIHIPortType
     */
    @WebEndpoint(name = "ConsumerUpdateIHISOAP12Port")
    public ConsumerUpdateIHIPortType getConsumerUpdateIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateIHI/3.2.0", "ConsumerUpdateIHISOAP12Port"), ConsumerUpdateIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERUPDATEIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERUPDATEIHISERVICE_EXCEPTION;
        }
        return CONSUMERUPDATEIHISERVICE_WSDL_LOCATION;
    }

}
