
package au.net.electronichealth.ns.hi.svc.consumersearchihibatchasync._3;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerSearchIHIBatchAsyncService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchAsync/3.0", wsdlLocation = "HI_ConsumerSearchIHIBatchAsync-3.0.wsdl")
public class ConsumerSearchIHIBatchAsyncService
    extends Service
{

    private static final URL CONSUMERSEARCHIHIBATCHASYNCSERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERSEARCHIHIBATCHASYNCSERVICE_EXCEPTION;
    private static final QName CONSUMERSEARCHIHIBATCHASYNCSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchAsync/3.0", "ConsumerSearchIHIBatchAsyncService");

    static {
        CONSUMERSEARCHIHIBATCHASYNCSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumersearchihibatchasync._3.ConsumerSearchIHIBatchAsyncService.class.getResource("HI_ConsumerSearchIHIBatchAsync-3.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERSEARCHIHIBATCHASYNCSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerSearchIHIBatchAsync-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERSEARCHIHIBATCHASYNCSERVICE_EXCEPTION = e;
    }

    public ConsumerSearchIHIBatchAsyncService() {
        super(__getWsdlLocation(), CONSUMERSEARCHIHIBATCHASYNCSERVICE_QNAME);
    }

    public ConsumerSearchIHIBatchAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERSEARCHIHIBATCHASYNCSERVICE_QNAME, features);
    }

    public ConsumerSearchIHIBatchAsyncService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERSEARCHIHIBATCHASYNCSERVICE_QNAME);
    }

    public ConsumerSearchIHIBatchAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERSEARCHIHIBATCHASYNCSERVICE_QNAME, features);
    }

    public ConsumerSearchIHIBatchAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerSearchIHIBatchAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerSearchIHIBatchAsyncPortType
     */
    @WebEndpoint(name = "ConsumerSearchIHIBatchAsyncSOAP12ServicePort")
    public ConsumerSearchIHIBatchAsyncPortType getConsumerSearchIHIBatchAsyncSOAP12ServicePort() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchAsync/3.0", "ConsumerSearchIHIBatchAsyncSOAP12ServicePort"), ConsumerSearchIHIBatchAsyncPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerSearchIHIBatchAsyncPortType
     */
    @WebEndpoint(name = "ConsumerSearchIHIBatchAsyncSOAP12ServicePort")
    public ConsumerSearchIHIBatchAsyncPortType getConsumerSearchIHIBatchAsyncSOAP12ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerSearchIHIBatchAsync/3.0", "ConsumerSearchIHIBatchAsyncSOAP12ServicePort"), ConsumerSearchIHIBatchAsyncPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERSEARCHIHIBATCHASYNCSERVICE_EXCEPTION!= null) {
            throw CONSUMERSEARCHIHIBATCHASYNCSERVICE_EXCEPTION;
        }
        return CONSUMERSEARCHIHIBATCHASYNCSERVICE_WSDL_LOCATION;
    }

}
