
package au.net.electronichealth.ns.hi.svc.providerreadreferencedata._3_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderReadReferenceDataService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderReadReferenceData/3.2.0", wsdlLocation = "HI_ProviderReadReferenceData-3.2.0.wsdl")
public class ProviderReadReferenceDataService
    extends Service
{

    private final static URL PROVIDERREADREFERENCEDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERREADREFERENCEDATASERVICE_EXCEPTION;
    private final static QName PROVIDERREADREFERENCEDATASERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadReferenceData/3.2.0", "ProviderReadReferenceDataService");

    static {
        PROVIDERREADREFERENCEDATASERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providerreadreferencedata._3_2.ProviderReadReferenceDataService.class.getResource("HI_ProviderReadReferenceData-3.2.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERREADREFERENCEDATASERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderReadReferenceData-3.2.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERREADREFERENCEDATASERVICE_EXCEPTION = e;
    }

    public ProviderReadReferenceDataService() {
        super(__getWsdlLocation(), PROVIDERREADREFERENCEDATASERVICE_QNAME);
    }

    public ProviderReadReferenceDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERREADREFERENCEDATASERVICE_QNAME, features);
    }

    public ProviderReadReferenceDataService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERREADREFERENCEDATASERVICE_QNAME);
    }

    public ProviderReadReferenceDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERREADREFERENCEDATASERVICE_QNAME, features);
    }

    public ProviderReadReferenceDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderReadReferenceDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderReadReferenceDataPortType
     */
    @WebEndpoint(name = "ProviderReadReferenceDataSOAP12Port")
    public ProviderReadReferenceDataPortType getProviderReadReferenceDataSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadReferenceData/3.2.0", "ProviderReadReferenceDataSOAP12Port"), ProviderReadReferenceDataPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderReadReferenceDataPortType
     */
    @WebEndpoint(name = "ProviderReadReferenceDataSOAP12Port")
    public ProviderReadReferenceDataPortType getProviderReadReferenceDataSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderReadReferenceData/3.2.0", "ProviderReadReferenceDataSOAP12Port"), ProviderReadReferenceDataPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERREADREFERENCEDATASERVICE_EXCEPTION!= null) {
            throw PROVIDERREADREFERENCEDATASERVICE_EXCEPTION;
        }
        return PROVIDERREADREFERENCEDATASERVICE_WSDL_LOCATION;
    }

}
