
package au.net.electronichealth.ns.hi.svc.consumercreateprovisionalihi._3;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsumerCreateProvisionalIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerCreateProvisionalIHI/3.0", wsdlLocation = "HI_ConsumerCreateProvisionalIHI-3.0.wsdl")
public class ConsumerCreateProvisionalIHIService
    extends Service
{

    private static final URL CONSUMERCREATEPROVISIONALIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException CONSUMERCREATEPROVISIONALIHISERVICE_EXCEPTION;
    private static final QName CONSUMERCREATEPROVISIONALIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateProvisionalIHI/3.0", "ConsumerCreateProvisionalIHIService");

    static {
        CONSUMERCREATEPROVISIONALIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumercreateprovisionalihi._3.ConsumerCreateProvisionalIHIService.class.getResource("HI_ConsumerCreateProvisionalIHI-3.0.wsdl");
        WebServiceException e = null;
        if (CONSUMERCREATEPROVISIONALIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerCreateProvisionalIHI-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERCREATEPROVISIONALIHISERVICE_EXCEPTION = e;
    }

    public ConsumerCreateProvisionalIHIService() {
        super(__getWsdlLocation(), CONSUMERCREATEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerCreateProvisionalIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERCREATEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerCreateProvisionalIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERCREATEPROVISIONALIHISERVICE_QNAME);
    }

    public ConsumerCreateProvisionalIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERCREATEPROVISIONALIHISERVICE_QNAME, features);
    }

    public ConsumerCreateProvisionalIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerCreateProvisionalIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerCreateProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateProvisionalIHISOAP12Port")
    public ConsumerCreateProvisionalIHIPortType getConsumerCreateProvisionalIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateProvisionalIHI/3.0", "ConsumerCreateProvisionalIHISOAP12Port"), ConsumerCreateProvisionalIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerCreateProvisionalIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateProvisionalIHISOAP12Port")
    public ConsumerCreateProvisionalIHIPortType getConsumerCreateProvisionalIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateProvisionalIHI/3.0", "ConsumerCreateProvisionalIHISOAP12Port"), ConsumerCreateProvisionalIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERCREATEPROVISIONALIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERCREATEPROVISIONALIHISERVICE_EXCEPTION;
        }
        return CONSUMERCREATEPROVISIONALIHISERVICE_WSDL_LOCATION;
    }

}
