
package au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderSearchForIndividualBatchAsyncService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", wsdlLocation = "HI_ProviderBatchAsyncSearchForProviderIndividual-5.1.0.wsdl")
public class ProviderSearchForIndividualBatchAsyncService
    extends Service
{

    private final static URL PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_EXCEPTION;
    private final static QName PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", "ProviderSearchForIndividualBatchAsyncService");

    static {
        PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1.ProviderSearchForIndividualBatchAsyncService.class.getResource("HI_ProviderBatchAsyncSearchForProviderIndividual-5.1.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderBatchAsyncSearchForProviderIndividual-5.1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_EXCEPTION = e;
    }

    public ProviderSearchForIndividualBatchAsyncService() {
        super(__getWsdlLocation(), PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_QNAME);
    }

    public ProviderSearchForIndividualBatchAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_QNAME, features);
    }

    public ProviderSearchForIndividualBatchAsyncService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_QNAME);
    }

    public ProviderSearchForIndividualBatchAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_QNAME, features);
    }

    public ProviderSearchForIndividualBatchAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderSearchForIndividualBatchAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchForProviderIndividualBatchAsyncPortType
     */
    @WebEndpoint(name = "ProviderSearchForIndividualBatchAsyncPort")
    public SearchForProviderIndividualBatchAsyncPortType getProviderSearchForIndividualBatchAsyncPort() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", "ProviderSearchForIndividualBatchAsyncPort"), SearchForProviderIndividualBatchAsyncPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchForProviderIndividualBatchAsyncPortType
     */
    @WebEndpoint(name = "ProviderSearchForIndividualBatchAsyncPort")
    public SearchForProviderIndividualBatchAsyncPortType getProviderSearchForIndividualBatchAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", "ProviderSearchForIndividualBatchAsyncPort"), SearchForProviderIndividualBatchAsyncPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_EXCEPTION!= null) {
            throw PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_EXCEPTION;
        }
        return PROVIDERSEARCHFORINDIVIDUALBATCHASYNCSERVICE_WSDL_LOCATION;
    }

}
