
package au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1;

import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ProductType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.SignatureContainerType;
import au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.TimestampType;
import au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.QualifiedId;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SearchForProviderIndividualBatchAsyncPortType", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.addresscore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.addresscore._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoreelements._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.individualnamecore._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.qualifiedidentifier._3.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.address._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.elements._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.individualname._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.personaldetails._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providercoreelements._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providercoreelements._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providertype._3_2.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providertype._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providercore.providertype._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providermessages.retrievesearchproviderindividual._5_1.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providermessages.searchindividual._5_0.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.providermessages.submitsearchproviderindividual._5_1.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    au.net.electronichealth.ns.hi.xsd.common.commoncoredatatypes._3.ObjectFactory.class
})
public interface SearchForProviderIndividualBatchAsyncPortType {


    /**
     * 
     * @param hpioHeader
     * @param productHeader
     * @param request
     * @param signatureHeader
     * @param timestampHeader
     * @param userHeader
     * @return
     *     returns au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1.SubmitSearchForProviderIndividualResponse
     * @throws StandardErrorMsg
     */
    @WebMethod
    @WebResult(name = "submitSearchForProviderIndividualResponse", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", partName = "response")
    @Action(input = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/submitSearchForProviderIndividualRequest", output = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/submitSearchForProviderIndividualResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/submitSearchForProviderIndividual/Fault/standardError")
    })
    public SubmitSearchForProviderIndividualResponse submitSearchForProviderIndividual(
        @WebParam(name = "submitSearchForProviderIndividual", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", partName = "request")
        SubmitSearchForProviderIndividual request,
        @WebParam(name = "product", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "productHeader")
        Holder<ProductType> productHeader,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "timestampHeader")
        TimestampType timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<SignatureContainerType> signatureHeader,
        @WebParam(name = "user", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "userHeader")
        QualifiedId userHeader,
        @WebParam(name = "hpio", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "hpioHeader")
        QualifiedId hpioHeader)
        throws StandardErrorMsg
    ;

    /**
     * 
     * @param hpioHeader
     * @param productHeader
     * @param request
     * @param signatureHeader
     * @param timestampHeader
     * @param userHeader
     * @return
     *     returns au.net.electronichealth.ns.hi.svc.providerbatchasyncsearchforproviderindividual._5_1.RetrieveSearchForProviderIndividualResponse
     * @throws StandardErrorMsg
     */
    @WebMethod
    @WebResult(name = "retrieveSearchForProviderIndividualResponse", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", partName = "response")
    @Action(input = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/retrieveSearchForProviderIndividualRequest", output = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/retrieveSearchForProviderIndividualResponse", fault = {
        @FaultAction(className = StandardErrorMsg.class, value = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0/SearchForProviderIndividualBatchAsyncPortType/retrieveSearchForProviderIndividual/Fault/standardError")
    })
    public RetrieveSearchForProviderIndividualResponse retrieveSearchForProviderIndividual(
        @WebParam(name = "retrieveSearchForProviderIndividual", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderBatchAsyncSearchForProviderIndividual/5.1.0", partName = "request")
        RetrieveSearchForProviderIndividual request,
        @WebParam(name = "product", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "productHeader")
        Holder<ProductType> productHeader,
        @WebParam(name = "timestamp", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "timestampHeader")
        TimestampType timestampHeader,
        @WebParam(name = "signature", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, mode = WebParam.Mode.INOUT, partName = "signatureHeader")
        Holder<SignatureContainerType> signatureHeader,
        @WebParam(name = "user", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "userHeader")
        QualifiedId userHeader,
        @WebParam(name = "hpio", targetNamespace = "http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0", header = true, partName = "hpioHeader")
        QualifiedId hpioHeader)
        throws StandardErrorMsg
    ;

}
