
package au.net.electronichealth.ns.hi.svc.providersearchforproviderorganisation._5_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderSearchForProviderOrganisationService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ProviderSearchForProviderOrganisation/5.0.0", wsdlLocation = "HI_ProviderSearchForProviderOrganisation-5.0.0.wsdl")
public class ProviderSearchForProviderOrganisationService
    extends Service
{

    private final static URL PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_EXCEPTION;
    private final static QName PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchForProviderOrganisation/5.0.0", "ProviderSearchForProviderOrganisationService");

    static {
        PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.providersearchforproviderorganisation._5_0.ProviderSearchForProviderOrganisationService.class.getResource("HI_ProviderSearchForProviderOrganisation-5.0.0.wsdl");
        WebServiceException e = null;
        if (PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ProviderSearchForProviderOrganisation-5.0.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_EXCEPTION = e;
    }

    public ProviderSearchForProviderOrganisationService() {
        super(__getWsdlLocation(), PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_QNAME);
    }

    public ProviderSearchForProviderOrganisationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_QNAME, features);
    }

    public ProviderSearchForProviderOrganisationService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_QNAME);
    }

    public ProviderSearchForProviderOrganisationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_QNAME, features);
    }

    public ProviderSearchForProviderOrganisationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderSearchForProviderOrganisationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderSearchForProviderOrganisationPortType
     */
    @WebEndpoint(name = "ProviderSearchForProviderOrganisationSOAP12Port")
    public ProviderSearchForProviderOrganisationPortType getProviderSearchForProviderOrganisationSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchForProviderOrganisation/5.0.0", "ProviderSearchForProviderOrganisationSOAP12Port"), ProviderSearchForProviderOrganisationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderSearchForProviderOrganisationPortType
     */
    @WebEndpoint(name = "ProviderSearchForProviderOrganisationSOAP12Port")
    public ProviderSearchForProviderOrganisationPortType getProviderSearchForProviderOrganisationSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ProviderSearchForProviderOrganisation/5.0.0", "ProviderSearchForProviderOrganisationSOAP12Port"), ProviderSearchForProviderOrganisationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_EXCEPTION!= null) {
            throw PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_EXCEPTION;
        }
        return PROVIDERSEARCHFORPROVIDERORGANISATIONSERVICE_WSDL_LOCATION;
    }

}
