
package au.net.electronichealth.ns.hi.svc.consumerupdateprovisionalihi._3;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UpdateProvisionalIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateProvisionalIHI/3.0", wsdlLocation = "HI_ConsumerUpdateProvisionalIHI-3.0.wsdl")
public class UpdateProvisionalIHIService
    extends Service
{

    private static final URL UPDATEPROVISIONALIHISERVICE_WSDL_LOCATION;
    private static final WebServiceException UPDATEPROVISIONALIHISERVICE_EXCEPTION;
    private static final QName UPDATEPROVISIONALIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateProvisionalIHI/3.0", "UpdateProvisionalIHIService");

    static {
        UPDATEPROVISIONALIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumerupdateprovisionalihi._3.UpdateProvisionalIHIService.class.getResource("HI_ConsumerUpdateProvisionalIHI-3.0.wsdl");
        WebServiceException e = null;
        if (UPDATEPROVISIONALIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'HI_ConsumerUpdateProvisionalIHI-3.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        UPDATEPROVISIONALIHISERVICE_EXCEPTION = e;
    }

    public UpdateProvisionalIHIService() {
        super(__getWsdlLocation(), UPDATEPROVISIONALIHISERVICE_QNAME);
    }

    public UpdateProvisionalIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEPROVISIONALIHISERVICE_QNAME, features);
    }

    public UpdateProvisionalIHIService(URL wsdlLocation) {
        super(wsdlLocation, UPDATEPROVISIONALIHISERVICE_QNAME);
    }

    public UpdateProvisionalIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEPROVISIONALIHISERVICE_QNAME, features);
    }

    public UpdateProvisionalIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateProvisionalIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerUpdateProvisionalIHIPortType
     */
    @WebEndpoint(name = "UpdateProvisionalIHISOAP12Port")
    public ConsumerUpdateProvisionalIHIPortType getUpdateProvisionalIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateProvisionalIHI/3.0", "UpdateProvisionalIHISOAP12Port"), ConsumerUpdateProvisionalIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerUpdateProvisionalIHIPortType
     */
    @WebEndpoint(name = "UpdateProvisionalIHISOAP12Port")
    public ConsumerUpdateProvisionalIHIPortType getUpdateProvisionalIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerUpdateProvisionalIHI/3.0", "UpdateProvisionalIHISOAP12Port"), ConsumerUpdateProvisionalIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEPROVISIONALIHISERVICE_EXCEPTION!= null) {
            throw UPDATEPROVISIONALIHISERVICE_EXCEPTION;
        }
        return UPDATEPROVISIONALIHISERVICE_WSDL_LOCATION;
    }

}
