
package au.net.electronichealth.ns.hi.svc.consumercreateunverifiedihi._3_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsumerCreateUnverifiedIHIService", targetNamespace = "http://ns.electronichealth.net.au/hi/svc/ConsumerCreateUnverifiedIHI/3.0.2", wsdlLocation = "/HI_ConsumerCreateUnverifiedIHI-3.0.2.wsdl")
public class ConsumerCreateUnverifiedIHIService
    extends Service
{

    private final static URL CONSUMERCREATEUNVERIFIEDIHISERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSUMERCREATEUNVERIFIEDIHISERVICE_EXCEPTION;
    private final static QName CONSUMERCREATEUNVERIFIEDIHISERVICE_QNAME = new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateUnverifiedIHI/3.0.2", "ConsumerCreateUnverifiedIHIService");

    static {
        CONSUMERCREATEUNVERIFIEDIHISERVICE_WSDL_LOCATION = au.net.electronichealth.ns.hi.svc.consumercreateunverifiedihi._3_0.ConsumerCreateUnverifiedIHIService.class.getResource("/HI_ConsumerCreateUnverifiedIHI-3.0.2.wsdl");
        WebServiceException e = null;
        if (CONSUMERCREATEUNVERIFIEDIHISERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/HI_ConsumerCreateUnverifiedIHI-3.0.2.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONSUMERCREATEUNVERIFIEDIHISERVICE_EXCEPTION = e;
    }

    public ConsumerCreateUnverifiedIHIService() {
        super(__getWsdlLocation(), CONSUMERCREATEUNVERIFIEDIHISERVICE_QNAME);
    }

    public ConsumerCreateUnverifiedIHIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSUMERCREATEUNVERIFIEDIHISERVICE_QNAME, features);
    }

    public ConsumerCreateUnverifiedIHIService(URL wsdlLocation) {
        super(wsdlLocation, CONSUMERCREATEUNVERIFIEDIHISERVICE_QNAME);
    }

    public ConsumerCreateUnverifiedIHIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSUMERCREATEUNVERIFIEDIHISERVICE_QNAME, features);
    }

    public ConsumerCreateUnverifiedIHIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsumerCreateUnverifiedIHIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsumerCreateUnverifiedIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateUnverifiedIHISOAP12Port")
    public ConsumerCreateUnverifiedIHIPortType getConsumerCreateUnverifiedIHISOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateUnverifiedIHI/3.0.2", "ConsumerCreateUnverifiedIHISOAP12Port"), ConsumerCreateUnverifiedIHIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsumerCreateUnverifiedIHIPortType
     */
    @WebEndpoint(name = "ConsumerCreateUnverifiedIHISOAP12Port")
    public ConsumerCreateUnverifiedIHIPortType getConsumerCreateUnverifiedIHISOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/hi/svc/ConsumerCreateUnverifiedIHI/3.0.2", "ConsumerCreateUnverifiedIHISOAP12Port"), ConsumerCreateUnverifiedIHIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSUMERCREATEUNVERIFIEDIHISERVICE_EXCEPTION!= null) {
            throw CONSUMERCREATEUNVERIFIEDIHISERVICE_EXCEPTION;
        }
        return CONSUMERCREATEUNVERIFIEDIHISERVICE_WSDL_LOCATION;
    }

}
